import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import { newId } from "@/lib/utils";
import type { BinderDoc, Column } from "./types";
import { blankDoc } from "./types";
import { guessFields } from "./guess";

const CASES = [
  {
    filename: "Innoventive Industries Ltd. v. ICICI Bank, (2018) 1 SCC 407.pdf",
    name: "Innoventive Industries Ltd. v. ICICI Bank",
    cite: "(2018) 1 SCC 407",
    paras: "27 – 33",
    body: [
      "INNOVENTIVE INDUSTRIES LTD. v. ICICI BANK",
      "(2018) 1 SCC 407",
      "",
      "The Supreme Court considered the interplay between the Maharashtra Relief Undertakings Act and the Insolvency and Bankruptcy Code, 2016.",
      "",
      "Held: Once an insolvency petition is admitted, a moratorium under Section 14 of the Code comes into effect. State legislation cannot stand in the way of the Code, which is a later central enactment occupying the field.",
      "",
      "The decision is frequently cited on the non-obstante clause in Section 238 and the primacy of the Code over inconsistent state statutes.",
    ],
  },
  {
    filename: "Swiss Ribbons Pvt. Ltd. v. Union of India, (2019) 4 SCC 17.pdf",
    name: "Swiss Ribbons Pvt. Ltd. v. Union of India",
    cite: "(2019) 4 SCC 17",
    paras: "43 – 52",
    body: [
      "SWISS RIBBONS PVT. LTD. v. UNION OF INDIA",
      "(2019) 4 SCC 17",
      "",
      "A constitutional challenge to various provisions of the Insolvency and Bankruptcy Code was rejected.",
      "",
      "Held: The Code is a beneficial legislation which puts the corporate debtor back on its feet, not a mere recovery legislation for creditors. Distinguishing financial and operational creditors is based on intelligible differentia.",
      "",
      "Use this authority for the object of the Code and the limited scope of a Section 9 defence at the admission stage.",
    ],
  },
  {
    filename: "Vidarbha Industries Power Ltd. v. Axis Bank Ltd., (2022) 8 SCC 352.pdf",
    name: "Vidarbha Industries Power Ltd. v. Axis Bank Ltd.",
    cite: "(2022) 8 SCC 352",
    paras: "56 – 64",
    body: [
      "VIDARBHA INDUSTRIES POWER LTD. v. AXIS BANK LTD.",
      "(2022) 8 SCC 352",
      "",
      "The Court considered whether Section 7 of the Code is mandatory once debt and default are shown.",
      "",
      "Held: The Adjudicating Authority may, in a fit case, exercise limited discretion even where a financial debt and default are established — though the discretion is not at large and must be guided by the facts.",
      "",
      "Subsequent benches have read Vidarbha narrowly. Flag the paragraphs you will actually open.",
    ],
  },
];

async function judgementPdf(lines: string[]): Promise<ArrayBuffer> {
  const pdf = await PDFDocument.create();
  const font = await pdf.embedFont(StandardFonts.TimesRoman);
  const bold = await pdf.embedFont(StandardFonts.TimesRomanBold);
  const page = pdf.addPage([595.28, 841.89]);
  let y = 780;
  lines.forEach((line, i) => {
    const f = i < 2 ? bold : font;
    const size = i < 2 ? 13 : 11;
    if (!line) {
      y -= 14;
      return;
    }
    page.drawText(line, { x: 72, y, size, font: f, color: rgb(0.1, 0.1, 0.1), maxWidth: 450 });
    y -= size * 1.55;
  });
  page.drawText("Sample authority generated by Binder Builder — replace with the certified copy.", {
    x: 72,
    y: 48,
    size: 8,
    font,
    color: rgb(0.4, 0.4, 0.4),
  });
  const bytes = await pdf.save();
  return bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength) as ArrayBuffer;
}

export async function makeSampleDocs(columns: Column[]): Promise<{ docs: BinderDoc[]; buffers: ArrayBuffer[] }> {
  const docs: BinderDoc[] = [];
  const buffers: ArrayBuffer[] = [];
  for (const c of CASES) {
    const buf = await judgementPdf(c.body);
    const doc = blankDoc({
      id: newId(),
      filename: c.filename,
      pageCount: 1,
      flagged: c.name.startsWith("Swiss"),
      kind: "authority",
      searchText: c.body.join(" "),
      holding: c.body.find((l) => l.startsWith("Held:")) || "",
    });
    guessFields(doc, columns);
    const caseCol = columns.find((col) => col.type === "case");
    if (caseCol) doc.fields[caseCol.id] = { name: c.name, cite: c.cite };
    const paraCol = columns.find((col) => col.type === "text" && /para/i.test(col.name));
    if (paraCol) doc.fields[paraCol.id] = c.paras;
    docs.push(doc);
    buffers.push(buf);
  }
  return { docs, buffers };
}
