/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BinderRouteImport } from './routes/binder'
import { Route as ChronoRouteImport } from './routes/chrono'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as HearingRouteImport } from './routes/hearing'
import { Route as MattersRouteImport } from './routes/matters'
import { Route as TemplatesRouteImport } from './routes/templates'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BinderRoute = BinderRouteImport.update({
  id: '/binder',
  path: '/binder',
  getParentRoute: () => rootRouteImport,
} as any)
const ChronoRoute = ChronoRouteImport.update({
  id: '/chrono',
  path: '/chrono',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const HearingRoute = HearingRouteImport.update({
  id: '/hearing',
  path: '/hearing',
  getParentRoute: () => rootRouteImport,
} as any)
const MattersRoute = MattersRouteImport.update({
  id: '/matters',
  path: '/matters',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/binder': typeof BinderRoute
  '/chrono': typeof ChronoRoute
  '/desk': typeof DeskRoute
  '/guide': typeof GuideRoute
  '/hearing': typeof HearingRoute
  '/matters': typeof MattersRoute
  '/templates': typeof TemplatesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/binder': typeof BinderRoute
  '/chrono': typeof ChronoRoute
  '/desk': typeof DeskRoute
  '/guide': typeof GuideRoute
  '/hearing': typeof HearingRoute
  '/matters': typeof MattersRoute
  '/templates': typeof TemplatesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/binder': typeof BinderRoute
  '/chrono': typeof ChronoRoute
  '/desk': typeof DeskRoute
  '/guide': typeof GuideRoute
  '/hearing': typeof HearingRoute
  '/matters': typeof MattersRoute
  '/templates': typeof TemplatesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/binder'
    | '/chrono'
    | '/desk'
    | '/guide'
    | '/hearing'
    | '/matters'
    | '/templates'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/binder'
    | '/chrono'
    | '/desk'
    | '/guide'
    | '/hearing'
    | '/matters'
    | '/templates'
  id:
    | '__root__'
    | '/'
    | '/binder'
    | '/chrono'
    | '/desk'
    | '/guide'
    | '/hearing'
    | '/matters'
    | '/templates'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BinderRoute: typeof BinderRoute
  ChronoRoute: typeof ChronoRoute
  DeskRoute: typeof DeskRoute
  GuideRoute: typeof GuideRoute
  HearingRoute: typeof HearingRoute
  MattersRoute: typeof MattersRoute
  TemplatesRoute: typeof TemplatesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/binder': {
      id: '/binder'
      path: '/binder'
      fullPath: '/binder'
      preLoaderRoute: typeof BinderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chrono': {
      id: '/chrono'
      path: '/chrono'
      fullPath: '/chrono'
      preLoaderRoute: typeof ChronoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hearing': {
      id: '/hearing'
      path: '/hearing'
      fullPath: '/hearing'
      preLoaderRoute: typeof HearingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matters': {
      id: '/matters'
      path: '/matters'
      fullPath: '/matters'
      preLoaderRoute: typeof MattersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BinderRoute: BinderRoute,
  ChronoRoute: ChronoRoute,
  DeskRoute: DeskRoute,
  GuideRoute: GuideRoute,
  HearingRoute: HearingRoute,
  MattersRoute: MattersRoute,
  TemplatesRoute: TemplatesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
