/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BinderRouteImport } from './routes/binder'
import { Route as ChronoRouteImport } from './routes/chrono'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as DocketRouteImport } from './routes/docket'
import { Route as FetchRouteImport } from './routes/fetch'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as HearingRouteImport } from './routes/hearing'
import { Route as ListingsRouteImport } from './routes/listings'
import { Route as MattersRouteImport } from './routes/matters'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as ToaRouteImport } from './routes/toa'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BinderRoute = BinderRouteImport.update({
  id: '/binder',
  path: '/binder',
  getParentRoute: () => rootRouteImport,
} as any)
const ChronoRoute = ChronoRouteImport.update({
  id: '/chrono',
  path: '/chrono',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const DocketRoute = DocketRouteImport.update({
  id: '/docket',
  path: '/docket',
  getParentRoute: () => rootRouteImport,
} as any)
const FetchRoute = FetchRouteImport.update({
  id: '/fetch',
  path: '/fetch',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const HearingRoute = HearingRouteImport.update({
  id: '/hearing',
  path: '/hearing',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsRoute = ListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const MattersRoute = MattersRouteImport.update({
  id: '/matters',
  path: '/matters',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const ToaRoute = ToaRouteImport.update({
  id: '/toa',
  path: '/toa',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/binder': typeof BinderRoute
  '/chrono': typeof ChronoRoute
  '/desk': typeof DeskRoute
  '/docket': typeof DocketRoute
  '/fetch': typeof FetchRoute
  '/guide': typeof GuideRoute
  '/hearing': typeof HearingRoute
  '/listings': typeof ListingsRoute
  '/matters': typeof MattersRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/templates': typeof TemplatesRoute
  '/toa': typeof ToaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/binder': typeof BinderRoute
  '/chrono': typeof ChronoRoute
  '/desk': typeof DeskRoute
  '/docket': typeof DocketRoute
  '/fetch': typeof FetchRoute
  '/guide': typeof GuideRoute
  '/hearing': typeof HearingRoute
  '/listings': typeof ListingsRoute
  '/matters': typeof MattersRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/templates': typeof TemplatesRoute
  '/toa': typeof ToaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/binder': typeof BinderRoute
  '/chrono': typeof ChronoRoute
  '/desk': typeof DeskRoute
  '/docket': typeof DocketRoute
  '/fetch': typeof FetchRoute
  '/guide': typeof GuideRoute
  '/hearing': typeof HearingRoute
  '/listings': typeof ListingsRoute
  '/matters': typeof MattersRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/templates': typeof TemplatesRoute
  '/toa': typeof ToaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/binder'
    | '/chrono'
    | '/desk'
    | '/docket'
    | '/fetch'
    | '/guide'
    | '/hearing'
    | '/listings'
    | '/matters'
    | '/settings'
    | '/tasks'
    | '/templates'
    | '/toa'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/binder'
    | '/chrono'
    | '/desk'
    | '/docket'
    | '/fetch'
    | '/guide'
    | '/hearing'
    | '/listings'
    | '/matters'
    | '/settings'
    | '/tasks'
    | '/templates'
    | '/toa'
  id:
    | '__root__'
    | '/'
    | '/binder'
    | '/chrono'
    | '/desk'
    | '/docket'
    | '/fetch'
    | '/guide'
    | '/hearing'
    | '/listings'
    | '/matters'
    | '/settings'
    | '/tasks'
    | '/templates'
    | '/toa'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BinderRoute: typeof BinderRoute
  ChronoRoute: typeof ChronoRoute
  DeskRoute: typeof DeskRoute
  DocketRoute: typeof DocketRoute
  FetchRoute: typeof FetchRoute
  GuideRoute: typeof GuideRoute
  HearingRoute: typeof HearingRoute
  ListingsRoute: typeof ListingsRoute
  MattersRoute: typeof MattersRoute
  SettingsRoute: typeof SettingsRoute
  TasksRoute: typeof TasksRoute
  TemplatesRoute: typeof TemplatesRoute
  ToaRoute: typeof ToaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/binder': {
      id: '/binder'
      path: '/binder'
      fullPath: '/binder'
      preLoaderRoute: typeof BinderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chrono': {
      id: '/chrono'
      path: '/chrono'
      fullPath: '/chrono'
      preLoaderRoute: typeof ChronoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docket': {
      id: '/docket'
      path: '/docket'
      fullPath: '/docket'
      preLoaderRoute: typeof DocketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fetch': {
      id: '/fetch'
      path: '/fetch'
      fullPath: '/fetch'
      preLoaderRoute: typeof FetchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hearing': {
      id: '/hearing'
      path: '/hearing'
      fullPath: '/hearing'
      preLoaderRoute: typeof HearingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings': {
      id: '/listings'
      path: '/listings'
      fullPath: '/listings'
      preLoaderRoute: typeof ListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matters': {
      id: '/matters'
      path: '/matters'
      fullPath: '/matters'
      preLoaderRoute: typeof MattersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/toa': {
      id: '/toa'
      path: '/toa'
      fullPath: '/toa'
      preLoaderRoute: typeof ToaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BinderRoute: BinderRoute,
  ChronoRoute: ChronoRoute,
  DeskRoute: DeskRoute,
  DocketRoute: DocketRoute,
  FetchRoute: FetchRoute,
  GuideRoute: GuideRoute,
  HearingRoute: HearingRoute,
  ListingsRoute: ListingsRoute,
  MattersRoute: MattersRoute,
  SettingsRoute: SettingsRoute,
  TasksRoute: TasksRoute,
  TemplatesRoute: TemplatesRoute,
  ToaRoute: ToaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
